### ISSUE TITLE
Accidental replacement of Datto -> Assurio for attribution

### ISSUE THREAD

**Issue by Conan-Kudo** [assuriosw/assurio-snap#16]
In 8539d911322662903128c51f0e71ca192596dfd1, you accidentally replaced `Datto` with `Assurio` in the note about it being a fork of `dattobd`. I suspect this was an unintentional mistake caused by a rather greedy Find+Replace. 😉 

It'd be great if you fixed this as soon as reasonably possible.

**Comment by anelson** [comment]
Thanks for the heads up @Conan-Kudo , sorry for the delayed triage.  We'll get this fixed shortly.
